"use client"
import React, { useEffect, useState } from 'react';
import '../../globals.css';
import Head from 'next/head';
import { Provider } from 'react-redux';
import store from '../../../store/store';
import Header from '../../../components/Header';
import Footer from '../../../components/Footer';
import HeroBanner from '../../../components/HeroBanner';
import ProductCard from '../../../components/ProductCard';
import Wrapper from '../../../components/Wrapper';

async function getProducts(id) {
    const res = await fetch(`http://127.0.0.1:3001/api/products?categories[0]=${id}`);
    const products = await res.json();
    return products;
}

async function getCategorieDetails(id) {
    try {
        const res = await fetch(`http://127.0.0.1:3001/api/categories/${id}`);
        const categorie = await res.json();
        return categorie;
    }
    catch (error) {
        console.log(error);
    }
}

function CategorieDetails({ params }) {
    const [categorie, setCategorie] = useState([]);
    const [products, setProducts] = useState([]);
    useEffect(() => {
        async function fetchCategorieDetails() {
            const categorie = await getCategorieDetails(params.id);
            if (!categorie || !categorie?.name) notFound();
            setCategorie(categorie);
        }
        fetchCategorieDetails();
    }, [params.id]);

    useEffect(() => {
        async function fetchProducts() {
            const products = await getProducts(categorie._id);
            setProducts(products);
        }
        fetchProducts();
    }, [categorie._id]);

    return (
        <>
            <Head>
                <title>Online Shoe Store | JS Dev Hindi</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link
                    rel="preconnect"
                    href="https://fonts.gstatic.com"
                    crossOrigin="true"
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&family=Urbanist:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
                    rel="stylesheet"
                />
            </Head>
            <Provider store={store}>
                <Header />
                <HeroBanner />
                <Wrapper>
                    {/* heading and paragaph start */}
                    <div className="text-center max-w-[800px] mx-auto my-[50px] md:my-[80px]">
                        <div className="text-[28px] md:text-[34px] mb-5 font-semibold leading-tight">
                            {categorie.name}
                        </div>
                        <div className="text-md md:text-xl">
                            {categorie.slug}
                        </div>
                    </div>
                    {/* heading and paragaph end */}

                    {/* products grid start */}
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 my-14 px-5 md:px-0">
                        {products.map((product) => (
                            <ProductCard key={product.id} product={product} />
                        ))}
                    </div>
                    {/* products grid end */}
                </Wrapper>
                <Footer />
            </Provider>
        </>
    );
}

export default CategorieDetails;
