'use client';
import './globals.css'
import { Inter } from 'next/font/google'
import { CartProvider } from "use-shopping-cart";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CartProvider
        // Enables local storage
        shouldPersist={true}
      ></CartProvider>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
